name: "ci"
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run unit tests and coverage
      run: |
        sudo apt-get update && sudo apt-get -y install \
          build-essential \
          libsystemd-dev
        pip install --upgrade pip
        pip install -r tests/requirements.txt
        make init
        python -m coverage run -m unittest
        python -m coverage report
        python -m coverage html
        coverage-badge -o htmlcov/coverage.svg
    - uses: actions/upload-artifact@v1
      with:
        name: coverage_page
        path: htmlcov/
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build documentation
      run: |
        sudo apt-get update && sudo apt-get -y install \
          build-essential \
          libsystemd-dev
        pip install --upgrade pip
        pip install -r docs/requirements.txt
        make init
        cd docs/ && make html
        python -m pybadges --left-text=docs --right-text=latest > build/html/docs.svg
    - uses: actions/upload-artifact@v1
      with:
        name: docs_page
        path: docs/build/html/
  deploy:
    runs-on: ubuntu-latest
    needs: [tests, docs]
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/download-artifact@master
      with:
        name: docs_page
        path: .
    - uses: actions/download-artifact@master
      with:
        name: coverage_page
        path: coverage/
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
  deploy_test:
    runs-on: ubuntu-latest
    needs: [tests, docs]
    steps:
    - uses: actions/checkout@v1
    - name: Setup docs build
      run: |
        mkdir -p docs/build/html/
        touch docs/build/html/.yesjekyll
    - uses: actions/download-artifact@master
      with:
        name: docs_page
        path: docs/build/html/
    - uses: actions/download-artifact@master
      with:
        name: coverage_page
        path: docs/build/html/coverage/
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/build/html/
